Shop/urls.py
# Shop Url configs
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path(''),
    path('customer/', include('customer.urls', namespace='customer')),
    path('', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace='api')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# Shop Url configs
from django.urls import path, include
from .views import UserListView, AddressDetailView, AddressListView, UserDetailView, CustomerDetailView, CustomerListView, CartItemListView, CartItemDetailView, OrderListView, OrderDetailView

app_name = 'api'

urlpatterns = [
    path('user-list', UserListView.as_view(), name='user-list'),
    path('address-list', AddressListView.as_view(), name='address-list'),
    path('user-detail/<pk>', UserDetailView.as_view(), name='user-detail'),
    path('address-detail/<pk>', AddressDetailView.as_view(), name='address-detail'),
    path('customer-detail/<pk>', CustomerDetailView.as_view(), name='customer-detail'),
    path('customer-list/', CustomerListView.as_view(), name='customer-list'),
    path('cartitem-detail/<pk>', CartItemDetailView.as_view(), name='cartitem-detail'),
    path('cartitem-list/', CartItemListView.as_view(), name='cartitem-list'),
    path('order-list/', OrderListView.as_view(), name='order-list'),
    path('order-detail/<pk>', OrderDetailView.as_view(), name='order-detail'),
]

customer/urls.py
from django.urls import path, include
from .views import UserRegisterView, UserLoginView, UserLogoutView, UserPasswordResetView, UserPasswordResetDoneView, \
    UserPasswordResetConfirmView, UserPasswordResetCompleteView, PanelView, UserAddressView, UserProfileView, \
     UserProfileEditView, UserProfileImageEditView, UserAddressCreateView, UserAddressDeleteView
    

app_name = 'customer'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user-register'),
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('logout/', UserLogoutView.as_view(), name='user-logout'),
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('panel/', PanelView.as_view(), name='panel'),
    path('address/<pk>', UserAddressView.as_view(), name='address-edit'),
    path('address/', UserAddressCreateView.as_view(), name='address-create'),
    path('address-delete/<pk>', UserAddressDeleteView.as_view(), name='address-delete'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/<pk>', UserProfileEditView.as_view(), name='profile-edit'),
    path('profile-image/<pk>', UserProfileImageEditView.as_view(), name='profile-image-edit'),
    
]

product/urls.py
from django.urls import path
from .views import index, CategoryDetail, ProductDetail, BrandList, BrandDetail, ProductList
app_name = 'product'

urlpatterns = [
    path('', index, name='home'),
    path('categories/<int:category_id>', CategoryDetail.as_view(), name='category-detail'),
    path('brands/', BrandList.as_view(), name='brand-list'),
    path('brands/<int:brand_id>', BrandDetail.as_view(), name='brand-detail'),
    path('products/<int:product_id>', ProductDetail.as_view(), name='product-detail'),
]

customer/models.py
from django.utils.translation import gettext as _
from django.db import models
from core.models import User
from core.models import BaseModel
import os


class Address(BaseModel):
    """
        Customer's Addresses (a customer can have multiple addresses)
    """
    city = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=100)
    address = models.TextField()
    customer = models.ForeignKey("Customer", on_delete=models.CASCADE, related_name='userAddress')

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.customer} : {self.city}-{self.address}'


def get_upload_path(instance, filename):
    return os.path.join(
        instance.id,
        instance.first_name, instance.last_name,
        filename
        )    


class Customer(BaseModel):
    
    gender_choices = (
        ('male', 'مذکر'),
        ('female', 'مونث')
        )

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_('User'), default=None, blank=True, null=True)
    image = models.FileField(default='Default-Images/default_user.png', upload_to='user_profiles/', blank=True, null=True, verbose_name='Profile Image')
    gender = models.CharField(choices=gender_choices, null=True, blank=True, verbose_name='Gender', max_length=10)

    class Meta:
        ordering = ['-created']
        permissions = [
            ('view_profile', 'Can view the customer profile page'),
            ('edit_user_info', 'Can edit the customer User info')
        ]

    def __str__(self):
        return f'{self.user}'

customer/forms.py
from django import forms
from customer.models import Address
from core.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password


class UserRegistrationForm(forms.Form):
    """
        Form For User Registration
    """
    gender_choices = (
        ('male', 'مذکر'),
        ('female', 'مونث')
    )
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    gender = forms.ChoiceField(choices=gender_choices, widget=forms.Select(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}), validators=[validate_password])
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput(attrs={'class': 'form-control'}), validators=[validate_password])

    def clean_phone(self):
        """
            Validate phone being unique
        """
        phone = self.cleaned_data['phone']
        if User.objects.filter(phone=phone).exists():
            raise ValidationError('This Phone Number already exists !')
        else:
            return phone

    def clean_email(self):
        """
            Validate email being unique
        """
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('This Email already exists !')
        else:
            return email

    def clean(self):
        """
            Validate Password and Confirm being Match
        """
        clean_data = super().clean()
        password = clean_data.get('password1')
        confirm = clean_data.get('password2')

        if password and confirm and password != confirm:
            raise ValidationError('Password is not match !')


class UserLoginForm(forms.Form):
    """
        Form For User Login
    """
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserAddressForm(forms.ModelForm):
    model = Address
    fields = ['city', 'postal_code', 'address']

customer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from .forms import UserRegistrationForm, UserLoginForm, UserAddressForm
from django.contrib.auth import authenticate, login, logout
from core.models import User
from django.contrib import messages
from .models import Address, Customer
from django.contrib.auth import views as auth_views
import sweetify
from order.models import Order
from order.cart import Cart
from customer.models import Customer
from django.views.generic import UpdateView, CreateView, DeleteView
from django import http
# Create your views here.


class UserRegisterView(View):
    """
        View for User Registration
    """
    template_name = 'customer/register.html'
    form = UserRegistrationForm

    def dispatch(self, request, *args, **kwargs):
        """
            checks if user is already logged in or not
        """
        if request.user.is_authenticated:  # a user is already logged in
            return redirect('product:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        """
            sends register template to customer
        """
        form = UserRegistrationForm
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        """
            gets Registration form data and validates
        """
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_user = User.objects.create_user(phone=cd['phone'], email=cd['email'], password=cd['password1'])
            Customer.objects.create(user=new_user, gender=cd['gender'])
            sweetify.toast(request, "you registered successfully", icon="success", timer=5000)
            return redirect('product:home')
        else:  # user sends wrong data in register form
            sweetify.toast(request, "some entries are invalid, try again", icon="error", timer=5000)
            return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    """
        View for User login
    """
    template_name = 'customer/login.html'
    form = UserLoginForm

    def setup(self, request, *args, **kwargs):
        self.cart = Cart(request)
        return super().setup(request, *args, **kwargs)


    def dispatch(self, request, *args, **kwargs):
        """
            checks if user is already logged in or not
        """
        if request.user.is_authenticated:
            return redirect('product:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        """
            sends login template to customer
        """
        return render(request, self.template_name, {'form': self.form()})

    def post(self, request):
        """
            gets Login form data and validates
        """
        form = self.form(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            user = authenticate(request, username=clean_data['phone'], password=clean_data['password1'])
            if user is not None:  # user exists and passed of authentication
                login(request, user)
                customer, created = Customer.objects.get_or_create(user=request.user)
                open_order, created = Order.objects.get_or_create(customer=customer, is_active=True)
                self.cart.session_merge_order(open_order)
                sweetify.toast(request, "you logged in successfully.", icon="success", timer=1500)
                return redirect('product:home')
            else:
                sweetify.toast(request, "username or password is not correct", icon="error", timer=1500)

        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    """
        View for User Logout
    """
    def get(self, request):
        logout(request)
        sweetify.toast(request, "You've been logged out successfully.", icon="success", timer=1500)
        return redirect('product:home')


class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'customer/password_reset_form.html'
    success_url = reverse_lazy('customer:password_reset_done')
    email_template_name = 'customer/password_reset_email.html'


class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'customer/password_reset_done.html'


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'customer/password_reset_confirm.html'
    success_url = reverse_lazy('customer:password_reset_complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'customer/password_reset_complete.html'


class PanelView(View):

    def get(self, request):
        recent_orders = Order.objects.filter(customer = request.user.customer, is_active=False)
        addresses = Address.objects.filter(customer = request.user.customer)
        return render(request, 'customer/panel.html', {'recent_orders': recent_orders, 'addresses':addresses})


class UserAddressView(UpdateView):
    template_name = 'customer/address_edit.html'
    model = Address
    fields = ['city', 'postal_code', 'address']
    success_url = reverse_lazy('customer:panel')

class UserAddressCreateView(CreateView):
    template_name = 'customer/address_create.html'
    model = Address
    fields = ['city', 'postal_code', 'address']
    success_url = reverse_lazy('customer:panel')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.customer = self.request.user.customer
        self.object.save()

        return http.HttpResponseRedirect(self.get_success_url())

class UserAddressDeleteView(DeleteView):
    model = Address
    success_url = reverse_lazy('customer:panel')
    


class UserProfileEditView(UpdateView):
    template_name = 'customer/profile_edit.html'
    model = User
    fields = ['first_name', 'last_name', 'email']
    success_url = reverse_lazy('customer:panel')

class UserProfileImageEditView(UpdateView):
    template_name = 'customer/profile_pic_edit.html'
    model = Customer
    fields = ['image']
    success_url = reverse_lazy('customer:panel')
class UserProfileView(View):
    def get(self, request):
        return render(request, 'customer/profile.html')

customer/templates/customer/__sidebar.html
{% load static %}
<div class="sidebar ">
    <div class="logo-details">
      <i><a href="{% url 'product:home' %}"><img class='rouinded-circle brand-image' src="{% static 'site-logo.png' %}"></a></i> 
      <span class="logo_name"><a href="{% url 'product:home' %}" style='color:white; text-decoration:none'> Ali Shop</a></span>
      
    </div>
    <ul class="nav-links">
      <li>
        <a href="{% url 'customer:panel' %}">
        <i class='bx bx-history'></i>
          <span class="link_name">Dashboard</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="{% url 'customer:panel' %}">Dashboard</a></li>
        </ul>
      </li>
      <li>
        <a href="{% url 'customer:profile'%} ">
        <i class='bx bx-history'></i>
          <span class="link_name">Profile</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="{% url 'customer:profile'%}">Profile</a></li>
        </ul>
      </li>
      {% comment %} <li>
        <div class="iocn-link">
          <a href="#">
            <i class='bx bx-collection' ></i>
            <span class="link_name">Orders</span>
          </a>
          <i class='bx bxs-chevron-down arrow' ></i>
        </div>
        <ul class="sub-menu">
          <li><a class="link_name" href="#">Orders</a></li>
          <li><a href="#">Recent orders</a></li>
          <li><a href="#">Orders status</a></li>
          <li><a href="#">Submited orders</a></li>
        </ul>
      </li> {% endcomment %}
      
      <li>
    <div class="profile-details">
      <div class="profile-content">
        <img src="{{user.customer.image.url}}" alt="profileImg">
      </div>
      <div class="name-job">
          
          {% if not user.first_name  %}
          <div class="profile_name">{{user.customer.phone}}</div>
          {% else %}
          <div class="profile_name">{{user.first_name}}</div>      
          {% endif %}
              
        <div class="job">{{user.email}}</div>
      </div>
      <a href="{% url 'customer:user-logout' %}"><i class='bx bx-log-out' ></i></a>
     </div>
      </li>
    </ul>
  </div>
  

customer/templates/customer/address_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--<title> Drop Down Sidebar Menu | CodingLab </title>-->
    <link rel="stylesheet" href="{% static 'css/panel.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
    
<body>
    {% include 'customer/__sidebar.html' %}
    <section class='home-section'>
        <div class="home-content">
            <form method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                {{ form }}
                <input type="submit" value="Confirm">
            </form>
        </div>
    </section>
</body>
</html>

customer/templates/customer/address_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--<title> Drop Down Sidebar Menu | CodingLab </title>-->
    <link rel="stylesheet" href="{% static 'css/panel.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
    
<body>
    {% include 'customer/__sidebar.html' %}
    <section class='home-section'>
        <div class="home-content">
            <form action="" method='POST'>
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" value='confirm'>
            </form>
        </div>
    </section>
</body>
</html>

customer/templates/customer/address_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--<title> Drop Down Sidebar Menu | CodingLab </title>-->
    <link rel="stylesheet" href="{% static 'css/panel.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
    
<body>
    {% include 'customer/__sidebar.html' %}
    <section class='home-section'>
        <div class="home-content">
            <form action="" method='POST'>
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" value='confirm'>
            </form>
        </div>
    </section>
</body>
</html>

customer/templates/customer/login.html
{% extends 'shop/_base.html' %}

{% block prod_nav %}{% endblock %}

{% block Slider %}{% endblock  %}

{% block Contents    %}
    

    
<div class="container-fluid">
    {% include 'shop/layouts/__messages.html' %}
    <div class="row justify-content-center">
        <div class="col-3 m-5">
            <div class="card mt-2" style="width: 20rem;">
                <div class="card-body">
                    <h5 class="card-title">Login</h5>
                    <form action="" class="form" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-warning mt-3">Login</button>
                    </form>
                    <div class="card-footer mt-3 text-center">
                        <a href="{% url 'customer:reset_password' %}" class="text-primary mt-3" style='text-decoration:none'> Forgot password ? </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

customer/templates/customer/panel.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <!--<title> Drop Down Sidebar Menu | CodingLab </title>-->
    <link rel="stylesheet" href="{% static 'css/panel.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>

  {% include 'customer/__sidebar.html' %}

  <section class="home-section">
    <div class="home-content">
      <i class='bx bx-menu' ></i>
      <span class="text"></span>
      {% block content %}
  

      <div class="container-fluid">
        <div class="row justify-content-around mt-4">
          
        
            
        
        <div class="row justify-content-around mt-4">
          <div class="col-5">
            <div class="card mb-3">
              <img src="{% static 'order.png' %}" class="card-img-top" style="max-height:350px; object-fit: cover;">
              <div class="card-header text-center">ًRecent Orders</div>
              <div class="card-body">
                {% for order in recent_orders  %} 
                <h5 class="card-title mt-3" style='font-size:1em;'><span style='color: #0e819b;text-shadow: 1px 1px 2px #b9e1db;'>Order Code: {{order.id}}</span><br> final price : <span style='font-size: 0.8rem;color: rgb(114 107 71)'>{{order.final_price}} Toomans </span></h5>
                <h5 style='color: gray; font-size:0.6em'>{{order.created}} </h5>
    
                {% for item in order.items.all  %}
                  <a href="{% url 'product:product-detail' item.product.id %}" style='text-decoration:none; line-height:2rem;'>
                    <p class="card-text"><small class="text-muted"><span><img src="{{item.product.images.first.pic.url}}" alt="" style='height:2rem; width:2rem; border-radius:50%;'></span>{{item.product.name}}</small></p>
                  </a>
                {% endfor %}
                  
                <hr>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="col-5">
            <div class="card mb-3">
              <img src="{% static 'loc.jpg' %}" class="card-img-top" style="max-height:350px; object-fit: cover;">
              <div class="card-header text-center">User Addresses</div>
              <div class="card-body">
                {% for address in addresses  %} 
                <h5 class="card-title">{{address.city}}</h5>
                <p class="card-text">{{address.address}}</p>
                <p class="card-text"><small class="text-muted">{{address.created}}</small>
                  <span>
                    <a href="{% url 'customer:address-edit' address.id %}">
                      <i class='bx bx-edit-alt'></i>
                    </a>
                    <a href="{% url 'customer:address-delete' address.id %}">
                      <i class='bx text-danger bxs-comment-x'></i>
                    </a>
                  </span>
                </p>
                <hr>
                {% endfor %}
                <a href="{% url 'customer:address-create' %}" style='text-decoration:none'>
                  <h5 style='color:rgb(35 159 165); font-size:0.8rem; margin-top:0.3rem;'>add a new address</h5>
                </a>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
      {% endblock content %}

    </div>
  </section>






  <script>
  let arrow = document.querySelectorAll(".arrow");
  for (var i = 0; i < arrow.length; i++) {
    arrow[i].addEventListener("click", (e)=>{
   let arrowParent = e.target.parentElement.parentElement;//selecting main parent of arrow
   arrowParent.classList.toggle("showMenu");
    });
  }
  let sidebar = document.querySelector(".sidebar");
  let sidebarBtn = document.querySelector(".bx-menu");
  console.log(sidebarBtn);
  sidebarBtn.addEventListener("click", ()=>{
    sidebar.classList.toggle("close");
  });
  </script>
</body>
</html>

customer/templates/customer/password_reset_complete.html
{% extends "shop/_base.html" %}

{% block Contents %}
    <p class="text-success">your password changed successfully.</p>
{% endblock %}

customer/templates/customer/password_reset_confirm.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body class="bg-dark">
<div class="container-fluid">
    <h3 class="text-white mt-5 text-center">Reset Password</h3>
    <div class="row justify-content-center">
        <div class="card">
            {% if validlink %}
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type='submit' class="btn btn-info">change</button>
            </form>
        {% else %}
            <p class="text-warning"> this link is invalid. please try again. </p>
        {% endif %}
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

customer/templates/customer/password_reset_done.html
{% extends "shop/_base.html" %}

{% block Contents %}
    <p class="text-success">we sent u an email</p>
{% endblock %}

customer/templates/customer/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'customer:password_reset_confirm' uidb64=uid token=token %}

customer/templates/customer/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--<title> Drop Down Sidebar Menu | CodingLab </title>-->
    <link rel="stylesheet" href="{% static 'css/panel.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
    
<body>
    {% include 'customer/__sidebar.html' %}
    <section class='home-section'>
        <div class="home-content">
            <div class="container-fluid">
                <div class="row m-0 justify-content-center">
                    <div class="col-9">
                        <div class="profile-card">
                            <div class="container-fluid">
                                <div class="row m-0 justify-content-center">
                                    <div class="profile-image col-12 text-center">
                                        <img class='img-fluid' style='border-radius: 50%; max-height:17rem; max-width:17rem;' src="{{request.user.customer.image.url}}" alt="">
                                    </div>
                                    <div class="col-12 text-center">
                                        <a href="{% url 'customer:profile-image-edit' request.user.customer.id%}" style='text-decoration:none'>
                                            <h5 style='color:rgb(35 159 165); font-size:0.8rem; margin-top:0.3rem;'>Change Photo</h5>
                                        </a>
                                    </div>
                                </div>
                                <div class="row m-0 justify-content-center">
                                    <div class="profile-body col-12 text-center" >
                                        <h4 class='text-black'>First Name</h4>
                                        {% if request.user.first_name %}
                                        <h5 class='text-secondary'>{{request.user.first_name}}</h5>
                                        <hr>    
                                        {% else %}
                                        <h5 class='text-secondary'>empty</h5>
                                        <hr>    

                                        {% endif %}
                                        <h4 class='text-black'>Last Name</h4>
                                        {% if request.user.last_name %}
                                        <h5 class='text-secondary'>{{request.user.last_name}}</h5>
                                        <hr>    
                                        {% else %}
                                        <h5 class='text-secondary'>empty</h5>
                                        <hr>    
                                        {% endif %}
                                        <h4 class='text-black'>Email</h4>
                                        {% if request.user.email %}
                                        <h5 class='text-secondary'>{{request.user.email}}</h5>
                                        <hr>    
                                        {% else %}
                                        <h5 class='text-secondary'>empty</h5>
                                        <hr>    
                                        {% endif %}
                                        <a href="{% url 'customer:profile-edit' request.user.customer.id %}" style='text-decoration:none'>
                                            <h5 style='color:rgb(35 159 165); font-size:0.8rem;'>Edit User Info</h5>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>