Shop/urls.py
# Shop Url configs
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path(''),
    path('customer/', include('customer.urls', namespace='customer')),
    path('', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace='api')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# Shop Url configs
from django.urls import path, include
from .views import UserListView, AddressDetailView, AddressListView, UserDetailView, CustomerDetailView, CustomerListView, CartItemListView, CartItemDetailView, OrderListView, OrderDetailView

app_name = 'api'

urlpatterns = [
    path('user-list', UserListView.as_view(), name='user-list'),
    path('address-list', AddressListView.as_view(), name='address-list'),
    path('user-detail/<pk>', UserDetailView.as_view(), name='user-detail'),
    path('address-detail/<pk>', AddressDetailView.as_view(), name='address-detail'),
    path('customer-detail/<pk>', CustomerDetailView.as_view(), name='customer-detail'),
    path('customer-list/', CustomerListView.as_view(), name='customer-list'),
    path('cartitem-detail/<pk>', CartItemDetailView.as_view(), name='cartitem-detail'),
    path('cartitem-list/', CartItemListView.as_view(), name='cartitem-list'),
    path('order-list/', OrderListView.as_view(), name='order-list'),
    path('order-detail/<pk>', OrderDetailView.as_view(), name='order-detail'),
]

customer/urls.py
from django.urls import path, include
from .views import UserRegisterView, UserLoginView, UserLogoutView, UserPasswordResetView, UserPasswordResetDoneView, \
    UserPasswordResetConfirmView, UserPasswordResetCompleteView, PanelView, UserAddressView, UserProfileView, \
     UserProfileEditView, UserProfileImageEditView, UserAddressCreateView, UserAddressDeleteView
    

app_name = 'customer'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user-register'),
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('logout/', UserLogoutView.as_view(), name='user-logout'),
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('panel/', PanelView.as_view(), name='panel'),
    path('address/<pk>', UserAddressView.as_view(), name='address-edit'),
    path('address/', UserAddressCreateView.as_view(), name='address-create'),
    path('address-delete/<pk>', UserAddressDeleteView.as_view(), name='address-delete'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/<pk>', UserProfileEditView.as_view(), name='profile-edit'),
    path('profile-image/<pk>', UserProfileImageEditView.as_view(), name='profile-image-edit'),
    
]

product/urls.py
from django.urls import path
from .views import index, CategoryDetail, ProductDetail, BrandList, BrandDetail, ProductList
app_name = 'product'

urlpatterns = [
    path('', index, name='home'),
    path('categories/<int:category_id>', CategoryDetail.as_view(), name='category-detail'),
    path('brands/', BrandList.as_view(), name='brand-list'),
    path('brands/<int:brand_id>', BrandDetail.as_view(), name='brand-detail'),
    path('products/<int:product_id>', ProductDetail.as_view(), name='product-detail'),
]

templates/shop/layouts/__messages.html
{% load sweetify %}
{% sweetify %}
{% if messages %}
    {% for msg in messages %}
        <p class="alert m-0 alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/shop/layouts/__navbar_product.html
{% load static %}

{% block Styles %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock  %}
    
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand text-dark" href="#" style="font-size:0.8em; font-weight:bolder"><span><img class='rounded-circle user-image' src="{% static 'site-logo.png' %}"></span>  Alireza Shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% for cat in cats %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ cat.name }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% for child in cat.children.all %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'product:category-detail' child.id %}">
                                        {{ child.name }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            <li>
                <div class="nav-item">
                    <a href="{% url 'product:brand-list' %}" class="nav-link">Brands</a>
                </div>
            </li>
                <div class="nav-item" style="position:absolute; right:2em; top:1.2em;font-family: 'BYekan'">
                    <a href="#" class="posision-relative" id="cart" style="text-decoration:none; color:black;">
                        سبد خرید
                        <i class="fa fa-shopping-cart" style="font-size:1.2em;"></i>
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" style="opacity:0.5;" id="cart-length">{{cart|length}}</span>
                    </a>
                </div>
            </ul>
        </div>
    </div>
</nav>
 

{% block Cart %}
    <sectoin id="cart-section">
        {% include 'order/cart.html' %}
    </sectoin>
{% endblock  %}
    

templates/shop/layouts/__navbar_user.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:rgb(35, 32, 44)">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'product:home' %}">Home</a>
                </li>
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:user-login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:user-register' %}">Register</a>
                    </li>
                {% else %}
                    <li class="nav-item" style='position:absolute; right: 5em'>
                        <a class="nav-link" href="{% url 'customer:user-logout' %}"><i class='bx bx-log-out'></i></a>
                    </li>
                    <li style="direction: rtl; position:absolute; right: 2em">
                        <a href ="{% url 'customer:panel' %}"><img class='user-image rounded-circle' src="{{user.customer.image.url}}" alt="80x80" data-holder-rendered="true"></a>
                        
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>