Shop/urls.py
# Shop Url configs
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path(''),
    path('customer/', include('customer.urls', namespace='customer')),
    path('', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace='api')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# Shop Url configs
from django.urls import path, include
from .views import UserListView, AddressDetailView, AddressListView, UserDetailView, CustomerDetailView, CustomerListView, CartItemListView, CartItemDetailView, OrderListView, OrderDetailView

app_name = 'api'

urlpatterns = [
    path('user-list', UserListView.as_view(), name='user-list'),
    path('address-list', AddressListView.as_view(), name='address-list'),
    path('user-detail/<pk>', UserDetailView.as_view(), name='user-detail'),
    path('address-detail/<pk>', AddressDetailView.as_view(), name='address-detail'),
    path('customer-detail/<pk>', CustomerDetailView.as_view(), name='customer-detail'),
    path('customer-list/', CustomerListView.as_view(), name='customer-list'),
    path('cartitem-detail/<pk>', CartItemDetailView.as_view(), name='cartitem-detail'),
    path('cartitem-list/', CartItemListView.as_view(), name='cartitem-list'),
    path('order-list/', OrderListView.as_view(), name='order-list'),
    path('order-detail/<pk>', OrderDetailView.as_view(), name='order-detail'),
]

product/urls.py
from django.urls import path
from .views import index, CategoryDetail, ProductDetail, BrandList, BrandDetail, ProductList
app_name = 'product'

urlpatterns = [
    path('', index, name='home'),
    path('categories/<int:category_id>', CategoryDetail.as_view(), name='category-detail'),
    path('brands/', BrandList.as_view(), name='brand-list'),
    path('brands/<int:brand_id>', BrandDetail.as_view(), name='brand-detail'),
    path('products/<int:product_id>', ProductDetail.as_view(), name='product-detail'),
]

product/models.py
from django.db import models
from core.models import BaseModel
from customer.models import Address
from core.models import BaseDiscount


class Category(BaseModel):
    """
        Category Model has Self Relation
    """
    name = models.CharField(max_length=100)
    thumbnail = models.FileField(default='Default-Images/default_category.png', upload_to='categories/')
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='children', null=True, blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.name}'


class Provider(BaseModel):
    """
        Provider Companies Bring Product lines of different brands
    """
    name = models.CharField(max_length=100, verbose_name='Company Name')
    description = models.TextField(max_length=100, verbose_name='Company Details', null=True, blank=True)
    address = models.OneToOneField(Address, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.name}'


class Brand(BaseModel):
    """
        Product's original brands
    """
    name = models.CharField(max_length=100, verbose_name='Brand Name')
    country = models.CharField(max_length=100, verbose_name='Brand Country')
    provider = models.ForeignKey(Provider, on_delete=models.SET_NULL, verbose_name='Brand Provider',
                                 null=True, blank=True)
    thumbnail = models.FileField(default='Default-Images/default_brand.png', upload_to='brands/')
    description = models.TextField(null=True, blank=True, verbose_name='Brand Details')

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.name} from {self.provider}'


class Discount(BaseDiscount):
    """
        Discount model for Products
    """
    expire_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        if self.type == 'percent':
            return f'{self.value}%'
        return f'{self.value}$'

class ProductImage(BaseModel):
    pic = models.FileField(default='Default-Images/product_default.jpg', upload_to='Products/', verbose_name='Product Images', blank=True, null=True)
    is_main = models.BooleanField(verbose_name='Is Main Image', default=False, null=True, blank=True)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='images',null=True, blank=True)

class Product(BaseModel):
    name = models.CharField(max_length=100, verbose_name='English name')
    fa_name = models.CharField(max_length=100, verbose_name='Farsi name', null=True, blank=True )
    description = models.TextField(null=True, blank=True, verbose_name='Description')
    slug = models.SlugField(null=True, blank=True)
    price = models.IntegerField(verbose_name='Price')
    category = models.ForeignKey(Category, verbose_name='Category',
                                 related_name='products', null=True,
                                 blank=True, on_delete=models.SET_NULL)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Brand',
                              related_name='products')
    discount = models.ForeignKey(Discount, on_delete=models.SET_NULL, null=True, blank=True,
                                 verbose_name='Discount', related_name='products', default=None)

    @property
    def final_price(self):
        return self.price - self.discount.profit_value(self.price) if self.discount else self.price
        
    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.name} {self.price}'

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Category, Product, Brand
# Create your views here.


def index(request):
    """
        This view just returns last 10 products in a home template
    """
    products = Product.objects.all()[:10]
    return render(request, 'product/index.html', {'products': products})


class CategoryDetail(View):
    """
        This view returns a requested category to show products of it
    """
    template_name = 'product/detail-category.html'

    def dispatch(self, request, *args, **kwargs):
        """
            checks if category has product or not
        """
        category: Category = Category.objects.get(id=kwargs['category_id'])
        if not category.products.all():  # category products is empty
            return redirect('product:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, category_id):
        """
            returns requested category
            :params: category_id
            :return: category
        """
        cat = Category.objects.get(id=category_id)
        return render(request, self.template_name, {'cat':cat})

class BrandList(View):
    """
        This View shows all existing brands with a button to show products of them
    """
    template_name = 'product/brands.html'

    def get(self, request):
        return render(request, self.template_name, {'brands': Brand.objects.all()})


class BrandDetail(View):
    """
        This view shows all existing products for a requested brand
    """
    template_name = 'product/detail-brand.html'

    def dispatch(self, request, *args, **kwargs):
        """
            checks if brand has product or not
        """
        brand: Brand = Brand.objects.get(id=kwargs['brand_id'])
        if not brand.products.all():  # category products is empty
            return redirect('product:brand-list')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, brand_id):
        """
            returns requested brand
            :params: brand_id
            :return: brand
        """
        brand = Brand.objects.get(id=brand_id)
        return render(request, self.template_name, {'brand': brand})

class ProductDetail(View):
    """
        this view returns more details about a requested product
    """
    template_name = 'product/detail-product.html'

    def setup(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, pk=kwargs['product_id'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, product_id):
        return render(request, self.template_name, {'product': self.product})

    def post(self, requset, product_id):
        pass

class ProductList(View):
    pass

product/templates/product/brands.html
{% extends 'shop/_base.html' %}
{% block Title %}Brands{% endblock %}

{% block Contents %}
    <div class="container-fluid">
        <div class="row justify-content-around p-4">
            {% for brand in brands %}
                <div class="col-12 col-sm-10 col-md-3 card p-0 text-center shadow-sm">
                    <img src="{{brand.thumbnail.url}}" class="card-img-top img-responsive img-fluid" style="max-height: 220px" alt="{{ brand.name }}">
                    <h3 class="text-primary card-title m-3 p-1">{{ brand.name }}</h3>
                    <p class="text-dark card-text p-1"><span style="font-weight: bolder">Country: </span>{{ brand.country }}</p>
                    {% if brand.provider %}
                        <p class="text-dark card-text p-1"><span style="font-weight: bolder">Provider: </span>{{ brand.provider.name }}</p>
                    {% endif %}
                {% if brand.description %}
                    <p class="text-black card-text  p-1"><span style="font-weight: bolder">Details: </span>{{ brand.description }}</p>
                {% endif %}
                    <a href="{% url 'product:brand-detail' brand.id %}" class="btn btn-primary m-2 p-1">Brand Products</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

product/templates/product/detail-brand.html
{% extends 'shop/_base.html' %}
{% block Title %}{{ brand.name }} | Products{% endblock %}

{% block Contents %}
    <div class="container-fluid">
        <div class="row pt-2 pb-5 justify-content-around">
            {% for product in brand.products.all %}
                {% include 'product/product_card.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

product/templates/product/detail-category.html
{% extends 'shop/_base.html' %}
{% block Title %}{{ category.name }} | Products{% endblock %}

{% block Contents %}
    <div class="container-fluid"  >
        <div class="row pt-2 pb-5 justify-content-around">
            {% for product in cat.products.all %}
                {% include 'product/product_card.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

product/templates/product/detail-product.html
{% extends 'shop/_base.html' %}
{% load static %}
{% block Title %}{{ product.name }}{% endblock %}

{% block Styles %}
    <link rel="stylesheet" href="{% static 'css/splide-skyblue.min.css' %}">
{% endblock  %}

{% block Contents %}
    <div class="container-fluid text-dark p-0 m-0"  style="background-color:rgb(245, 245, 245)">
        <div class="row justify-content-center m-0">
            <div class="col-12 col-sm-6 p-5">
                <div id="image-slider" class="splide">
                    <div class="splide__track">
                        <ul class="splide__list">
                            {% for image in product.images.all %}
                                <li class="splide__slide">
                                    <img src="{{image.pic.url}}">
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div id="thumbnail-slider" class="splide mt-3">
                    <div class="splide__track">
                        <ul class="splide__list">
                            {% for image in product.images.all %}
                                <li class="splide__slide">
                                    <img src="{{image.pic.url}}">
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 p-3">
                <div class="row">
                    {% if product.category %}
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item" class="text-primary" style="text-decoration:none;">{{ product.category.parent.name }}</li>
                        <li class="breadcrumb-item active" aria-current="page"><a class="text-primary" href="{% url 'product:category-detail' product.category.id %}" style="text-decoration:none;">{{ product.category.name }}</a></li>
                        </ol>
                    {% endif %}
                    <h1 class="text-dark mt-3 p-2" style="direction:rtl; font-family:'Byekan'">{{ product.fa_name }}</h1>
                    <h2 class="text-dark mt-3 p-2" style="direction:rtl">{{ product.name }}</h2>
                    <p class=" p-1" style="color:rgb(97, 97, 97); direction:rtl; font-family:'Byekan'">{{ product.description }}</p>
                    <hr>
                    {% if product.discount %}
                        <h5 class="text-danger" style="direction:rtl; font-size: 1em; font-family: 'BYekan';">تخفیف ویژه : <span class="badge bg-danger">{{ product.discount }}</span></h5>
                        <div class='' style="direction:rtl; text-align: -webkit-center;"><h6 class="product-old-price" style="text-align:center; font-family:'BYekan';">{{product.price}} تومان</h6></div>
                        <h4 class="" style="direction:rtl; text-align: center; font-family:'BYekan'">{{product.final_price}}  تومان</h4>
                    {% else %}
                        <p class="text-black card-text p-1" style="text-align:center; font-weight:bolder; font-family:'BYekan'; direction:rtl">{{ product.price }} تومان</p>
                    {% endif %}
                </div>
                <div class="row justify-content-center">
                    <div class="col-12 col-sm-2">
                        <span>
                            <div class="quantity">
                                <input type="number" min="1" max="9" step="1" value="1" id="quantity-{{product.id}}" style="font-family:'BYekan'">
                            </div>
                        </span>
                    </div>
                    <div class="col-12 col-sm-3">
                        <button data-order="{{open_order}}" onclick="AddToCart('{{product.id}}', '{{request.user.is_authenticated}}')" class="button-2" style="font-family:'BYekan'" id="add-to-cart-button">
                            اضافه به سبد</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}



{% block Scripts %}
    <script src="{% static 'javascript/splide.min.js' %}"></script>
    <script>
        let main = new Splide( '#image-slider', {
            
            height:700 ,
            fixedheight: 400,
            heightRatio: 0.55,
            cover      : true,
            type: 'loop',
            pagination: false,
            arrows: false,
            
        } );
        let thumbnails = new Splide( '#thumbnail-slider', {
            fixedWidth  : 100,
            fixedHeight : 60,
            gap         : 0,
            rewind      : true,
            pagination  : false,
            cover       : true,
            isNavigation: true,
            breakpoints : {
                600: {
                    fixedWidth : 60,
                    fixedHeight: 44,
                },
            },
        } );
        main.sync( thumbnails );
        main.mount();
        thumbnails.mount();

    </script>
    <script>
        jQuery('<div class="quantity-nav"><div class="quantity-button quantity-up">+</div><div class="quantity-button quantity-down">-</div></div>').insertAfter('.quantity input');
        jQuery('.quantity').each(function() {
          var spinner = jQuery(this),
            input = spinner.find('input[type="number"]'),
            btnUp = spinner.find('.quantity-up'),
            btnDown = spinner.find('.quantity-down'),
            min = input.attr('min'),
            max = input.attr('max');

          btnUp.click(function() {
            var oldValue = parseFloat(input.val());
            if (oldValue >= max) {
              var newVal = oldValue;
            } else {
              var newVal = oldValue + 1;
            }
            spinner.find("input").val(newVal);
            spinner.find("input").trigger("change");
          });

          btnDown.click(function() {
            var oldValue = parseFloat(input.val());
            if (oldValue <= min) {
              var newVal = oldValue;
            } else {
              var newVal = oldValue - 1;
            }
            spinner.find("input").val(newVal);
            spinner.find("input").trigger("change");
          });

        });
    </script>
{% endblock  %}

product/templates/product/index.html
{% extends 'shop/_base.html' %}
{% block Title %}خانه{% endblock %}

{% block Contents %}
    <div class="container-fluid">
        <div class="row pt-2 pb-5 justify-content-between">
            {% for product in products %}
                {% include 'product/product_card.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block Scripts %}
    <script>
        jQuery('<div class="quantity-nav"><div class="quantity-button quantity-up">+</div><div class="quantity-button quantity-down">-</div></div>').insertAfter('.quantity input');
        jQuery('.quantity').each(function() {
          var spinner = jQuery(this),
            input = spinner.find('input[type="number"]'),
            btnUp = spinner.find('.quantity-up'),
            btnDown = spinner.find('.quantity-down'),
            min = input.attr('min'),
            max = input.attr('max');

          btnUp.click(function() {
            var oldValue = parseFloat(input.val());
            if (oldValue >= max) {
              var newVal = oldValue;
            } else {
              var newVal = oldValue + 1;
            }
            spinner.find("input").val(newVal);
            spinner.find("input").trigger("change");
          });

          btnDown.click(function() {
            var oldValue = parseFloat(input.val());
            if (oldValue <= min) {
              var newVal = oldValue;
            } else {
              var newVal = oldValue - 1;
            }
            spinner.find("input").val(newVal);
            spinner.find("input").trigger("change");
          });

        });
    </script>
{% endblock  %}
    

product/templates/product/product_card.html
<div class="col-12 col-sm-10 col-md-3 card p-0 pb-3 m-4 text-center display-relative rounded shadow-sm" style="max-height:30em;">
    <div class="container" style="height:100%;">
        <div class="row" id="image-section" style="align-content:center">
            
            {% if product.discount %}
                <div class="discount-badge"><span class="amount">{{product.discount}}</span><span class="icon fa fa fa-gift"></span></div>
            {% endif %}
                            
            <div class="col-12">
                <img src="{{product.images.first.pic.url}}" class="card-img-top img-responsive img-fluid" style="height:15em; object-fit: contain;" alt="{{ product.name }}">
            </div>
        </div>        
        <div class="row">
            <div class="col-12">
                <a href="{% url 'product:product-detail' product.id %}" style="text-decoration:none; color:rgb(53, 53, 53)">
                    <h5 class="card-title m-1 p-1" style="font-size:0.9em; white-space:nowrap;">{{ product.name }}</h5>
               </a>
            </div>
            <div class="col-12">
                <p class="card-text p-1" style="color:rgb(100, 100, 100); font-family:'BYekan'; direction:rtl">{{ product.price }} تومان</p>
            </div>
        </div>
    <!-- <p class="text-dark card-text p-1">{{ product.description|truncatewords:10 }}</p> -->
    <hr>
    <div class="row">
        <div class="col-12 col-sm-5">
            <span>
                <div class="quantity">
                    <input type="number" min="1" max="9" step="1" value="1" id="quantity-{{product.id}}" style="font-family:'BYekan'">
                </div>
            </span>
        </div>
        <div class="col-12 col-sm-7">
            <button data-order="{{open_order}}" onclick="AddToCart('{{product.id}}', '{{request.user.is_authenticated}}')" class="button-2" style="font-family:'BYekan'" id="add-to-cart-button">
                اضافه به سبد</button>
        </div>
    </div>
    </div>
</div>