Shop/urls.py
# Shop Url configs
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path(''),
    path('customer/', include('customer.urls', namespace='customer')),
    path('', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace='api')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# Shop Url configs
from django.urls import path, include
from .views import UserListView, AddressDetailView, AddressListView, UserDetailView, CustomerDetailView, CustomerListView, CartItemListView, CartItemDetailView, OrderListView, OrderDetailView

app_name = 'api'

urlpatterns = [
    path('user-list', UserListView.as_view(), name='user-list'),
    path('address-list', AddressListView.as_view(), name='address-list'),
    path('user-detail/<pk>', UserDetailView.as_view(), name='user-detail'),
    path('address-detail/<pk>', AddressDetailView.as_view(), name='address-detail'),
    path('customer-detail/<pk>', CustomerDetailView.as_view(), name='customer-detail'),
    path('customer-list/', CustomerListView.as_view(), name='customer-list'),
    path('cartitem-detail/<pk>', CartItemDetailView.as_view(), name='cartitem-detail'),
    path('cartitem-list/', CartItemListView.as_view(), name='cartitem-list'),
    path('order-list/', OrderListView.as_view(), name='order-list'),
    path('order-detail/<pk>', OrderDetailView.as_view(), name='order-detail'),
]

customer/urls.py
from django.urls import path, include
from .views import UserRegisterView, UserLoginView, UserLogoutView, UserPasswordResetView, UserPasswordResetDoneView, \
    UserPasswordResetConfirmView, UserPasswordResetCompleteView, PanelView, UserAddressView, UserProfileView, \
     UserProfileEditView, UserProfileImageEditView, UserAddressCreateView, UserAddressDeleteView
    

app_name = 'customer'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user-register'),
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('logout/', UserLogoutView.as_view(), name='user-logout'),
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('panel/', PanelView.as_view(), name='panel'),
    path('address/<pk>', UserAddressView.as_view(), name='address-edit'),
    path('address/', UserAddressCreateView.as_view(), name='address-create'),
    path('address-delete/<pk>', UserAddressDeleteView.as_view(), name='address-delete'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/<pk>', UserProfileEditView.as_view(), name='profile-edit'),
    path('profile-image/<pk>', UserProfileImageEditView.as_view(), name='profile-image-edit'),
    
]

order/urls.py
from django.urls import path
from .views import CartView, CartList, CartDetails, CartItemDelete, Payment, OffCodeCheck
app_name = 'order'

urlpatterns = [
    path('cart_details/' , CartDetails.as_view(), name='cart-details'),
    path('get_cart/' , CartList.as_view(), name='cart-list'),
    path('delete_cart_item/<int:product_id>' , CartItemDelete.as_view(), name='item-delete'),
    path('offcode_check', OffCodeCheck.as_view(), name='offcode-check'),
    path('add_to_cart/<int:product_id>/<int:quantity>', CartView.as_view(), name='add-to-cart'),
    path('payment/', Payment.as_view(), name='payment')
]

order/models.py
from django.db import models
from django.utils import timezone
from core.models import BaseDiscount, BaseModel
from customer.models import Customer, Address
from product.models import Product


class Coupon(BaseDiscount):
    code = models.CharField(max_length=50)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        if self.type == 'percent':
            return f'{self.code}| {self.value}%'
        return f'{self.code}| {self.value}$'


class CartItem(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Item')
    quantity = models.IntegerField(default=1, verbose_name='Quantity')
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='items', null=True, blank=True)
    final_price = models.IntegerField(default=0, null=True, blank=True)

    class Meta:
        ordering = ['-created']

    def calc_final_price(self):
        """
        Calculate and Return the Final Price of an order item
        :param: instance
        :return final_price:
        """
        self.final_price = (self.product.price - self.product.discount.profit_value(self.product.price)) * self.quantity if self.product.discount else self.product.price * self.quantity

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        """
            sets final price automatically before saving the model object
        """
        self.calc_final_price()
        return super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return f'{self.product.name}: {self.quantity}x'


class Order(BaseModel):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE,
                                    verbose_name='Customer', related_name='orders',
                                    null=True, blank=True)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True)
    final_price = models.IntegerField(default=0, null=True, blank=True)
    total_price = models.IntegerField(default=0, null=True, blank=True)

    class Meta:
        ordering = ['-created']

    def calc_total_price(self):
        """
            Calculate and return total_price of Cart
            :param: self
            :return total_price:
        """
        self.total_price = sum([x.final_price for x in self.items.all()])

    def calc_final_price(self):
        """
            Calculate and return final_price of Cart (with Coupon)
            :param: self
            :return final_price:
        """
        self.final_price = (self.total_price - self.coupon.profit_value(self.final_price)) if self.coupon else self.total_price

    def close_order(self):
        self.is_active = False

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        """
            sets final and total price automatically before saving the model object
        """
        self.calc_total_price()
        self.calc_final_price()
        return super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return f'{self.customer} - {self.final_price}'

order/forms.py
from django import forms
from customer.models import Address, Customer
class AddressForm(forms.Form):
    address = forms.ModelChoiceField(queryset=None, widget=forms.Select(attrs={'class':'form-select'}), label='')

    def __init__(self, customer, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['address'].queryset = Address.objects.filter(customer=customer)

order/views.py
from django.utils import timezone
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import HttpResponse, JsonResponse
from django.views import View
import sweetify
from customer.models import Address
from .cart import Cart
from product.models import Product
from django.shortcuts import get_object_or_404
from order.forms import AddressForm
from .models import Order, Coupon
from django.contrib.auth.mixins import LoginRequiredMixin


class CartView(View):

    def setup(self, request, *args, **kwargs):
        self.cart = Cart(request)
        return super().setup(request, *args, **kwargs)  

    def post(self,request, product_id, quantity):
        product = get_object_or_404(Product, pk=product_id)
        self.cart.add(product, quantity)
        return JsonResponse({'TotalItems': self.cart.__len__(), 'url':reverse('order:cart-list')}, safe=False)
    
    

class CartList(View):
    template_name = 'order/cart.html'

    def get(self, request):
        return render(request, self.template_name)

class CartDetails(LoginRequiredMixin, View):
    template_name = 'order/cart_detail.html'
    def get(self, request):
        return render(request, self.template_name, { 'address_form':AddressForm(customer=request.user.customer)})  

class CartItemDelete(View):

    def setup(self, request, *args, **kwargs):
        self.cart = Cart(request)
        return super().setup(request, *args, **kwargs)

    def delete(self, request, product_id):
        product = get_object_or_404(Product, pk=product_id)
        self.cart.remove(product=product)
        return JsonResponse({'TotalItems': self.cart.__len__(), 'url':reverse('order:cart-list'), 'total_price':self.cart.get_total_price()}, safe=False)

class Payment(View):

    def setup(self, request, *args, **kwargs) -> None:
        self.cart = Cart(request)
        return super().setup(request, *args, **kwargs)

    def post(self,request):
        address = Address.objects.get(id=request.POST['address'])
        open_order = Order.objects.get(customer=request.user.customer, is_active=True)
        open_order.address = address
        
        open_order.deactivate()
        
        open_order.save()
        
        self.cart.clear()
        
        
        Order.objects.create(customer=request.user.customer)
        sweetify.toast(request, "Your Order Submitted Successfully.", icon="success", timer=1500)

        return redirect('product:home')


class OffCodeCheck(View):
    def setup(self, request, *args, **kwargs):
        offcode = request.POST.get('offCode')
        self.offcode = Coupon.objects.filter(code = offcode, is_active = True,
                                             valid_from__lte = timezone.now(),
                                             valid_to__gte = timezone.now())
        self.offcode = self.offcode.first() if self.offcode.exists() else None
        print(self.offcode)
        self.open_order = Order.objects.get(customer=request.user.customer, is_active=True) 
        return super().setup(request, *args, **kwargs)


    def post(self, request):
        if not self.offcode:
            return JsonResponse({'msg': 'NotValid'}, safe=False)
        if self.open_order.coupon:
            self.open_order.coupon = None
            self.open_order.save()
            self.open_order.coupon = self.offcode
            self.open_order.save()
        else:
            self.open_order.coupon = self.offcode
            self.open_order.save()
        print(self.open_order.final_price)
        return JsonResponse({"msg": 'Success', "final_price": self.open_order.final_price}, safe=False)

order/templates/order/cart.html
<div class="shopping-cart" style="display:none;font-family:'BYekan'" id="shopping-cart">
  <div class="shopping-cart-header">
    <i class="fa fa-shopping-cart cart-icon"></i><span class="badge">{{cart|length}}</span>
    <div class="shopping-cart-total">
      <span class="lighter-text">قیمت کل:</span>
      <span class="main-color-text">{{cart.get_total_price}}</span>
    </div>
  </div> <!--end shopping-cart-header -->

  <ul class="shopping-cart-items">
    
    {% for item in cart %} 
    <li class="clearfix" >
      <span><img src="{{item.image}}" class='user-image rounded-circle' alt="item1" /></span>
      <span class="item-name">{{item.name}}</span>
      <span class="item-price">{{item.total_price}} تومان</span>
      <br>
      <span class="item-quantity">{{item.quantity}} عدد</span> 
    </li>
    {% endfor %}
  </ul>

  <a href="{% url 'order:cart-details' %}" class="button-2 w-100">details</a>
</div> <!--end shopping-cart -->

order/templates/order/cart_detail.html
{% extends 'shop/_base.html' %}
{% load static %}
{% block Title %}Cart Detail{% endblock %}


{% block Styles %}
    <link rel="stylesheet" href="{% static 'css/cart-detail.css' %}">
{% endblock  %}
    

{% block Contents %}
<div class="wrap cf" style="direction:rtl; font-family:'BYekan'!important" id="cart-detail">
    <h1 class="projTitle">سبد خرید</h1>
    <div class="cart">
      <ul class="cartWrap">
        
        {% for item in cart %}
        <li class="items">
            <div class="infoWrap"> 
                <div class="cartSection">
                    <img src="{{item.image}}" alt="item.name" class="itemImg" />
                    <h3 style="margin-top:1.5em; font-family:'BYekan'">{{item.name}}</h3>
                    <p style="font-family:BYekan"> تعداد: {{item.quantity}}</p>
                </div>  
            
                
                <div class="prodTotal cartSection">
                  <p style="font-family:'BYekan'">{{item.total_price}} تومان</p>
                </div>
                      <div class="cartSection removeWrap">
                   <a href="#" onclick="deleteItem('{{item.id}}')" class="remove">x</a>
                </div>
              </div>
              </li>
        {% endfor %}
            
      </ul>
    </div>
    
    <div class="promoCode"><label for="promo">اگر کد تخفیف دارید در اینجا وارد کنید</label><input type="text" name="promo" placeholder="کد تخفیف ..." / id="offcode">
      <a href="#" onclick="offCodeCheck(`{% url 'order:offcode-check' %}`)" class="btn"  ></a></div>
    <form action="{% url 'order:payment' %}" method='POST'>
    <div class="promoCode"><label for="promo">آدرس خود را انتخاب کنید</label>
      {{address_form}}
      <a href="{% url 'customer:address-create' %}">
        <h5 style='font-size:0.8rem; color:rgb(35 159 165); margin-top:0.4rem;'>
          اضافه کردن آدرس جدید
        </h5>
      </a>
      </div>
    
    <div class="subtotal cf">
      <ul>
        <li class="totalRow"><span class="label" style="font-family:'BYekan'">قیمت کل</span><span class="value" id='cart-total-price'>{{cart.get_total_price}} تومان</span></li>     
        <li class="totalRow"><button class='btn btn-success' type='submit' style='font-family:"BYekan"' id='paymentButton'>پرداخت</button></li>
      </ul>
    </div>
    {% csrf_token %}
  </form>
  </div>
  
{% endblock  %}
    

{% block Scripts %}
    <script>
      
      $('#paymentButton').prop('disabled', true)


        // Remove Items From Cart
      $('a.remove').click(function(){
        event.preventDefault();
        $( this ).parent().parent().parent().hide( 400 );
      
      })

      // Just for testing, show all items
        $('a.btn.continue').click(function(){
          $('li.items').show(400);
        })
      $('#id_address').change(()=>{
        if($('#id_address').val() == ''){
          $('#paymentButton').prop('disabled', true)
        }else{
          let cartLen = Number("{{cart | length}}")
          if(cartLen > 0){
            $('#paymentButton').prop('disabled', false)
          }
        }
      })
    </script>
{% endblock  %}
    